export enum UserUrls  {
    home = '/',
    signIn = '/signin',
    signUp = '/signup',
    otp = '/otp',
    signOut = '/signout',
    forgotPassword = '/forgotpassword',
    setNewPassword = '/resetpassword/:token',
    profile = '/profile',
    subscription = '/subscription',
    dashboard = '/dashboard',
    about = '/about',
    contact = '/contact',
    chat = '/chat',
    call = '/call',
    videoCall = '/video-call',
    listMentors = '/listmentors',
    mentorProfile = '/mentorprofile',
    booking = "/booking",
    bookingSucess = '/bookingsuccess',
    subscriptionSucess = "/subscriptionsuccess",
    notifications = '/notifications',
    paymetnCalcel = '/cancel',
    listBookings = '/listbookings'
}