export enum UserUrls  {
    home = '/',
    signIn = '/signin',
    signUp = '/signup',
    otp = '/otp',
    signOut = '/signout',
    forgotPassword = '/forgotpassword',
    setNewPassword = '/resetpassword/:token',
    profile = '/profile',
    subscription = '/subscription',
    dashboard = '/dashboard',
    about = '/about',
    contact = '/contact',
    chat = '/chat',
    call = '/call',
    videoCall = '/videocall',
    listMentors = '/listmentors',
    mentorProfile = '/mentorprofile',
    notifications = '/notifications',
}