export enum CommonApiEndPoints {
  changePassword = "/auth/common/changepassword",
  countactUs = "/user/common/contactus",
  sendMessage = "/chat/common/createmessage",
  fetchMessages = "/chat/common/fetchMessages",
  fetchMessageFromS3 = "/chat/common/fetchmessagefroms3",
  fetchWallet = "/payment/common/fetchwallet",
  createWallet = "/payment/common/createwallet",
  updateWalletName = "/payment/common/updatewalletname",
  fetchContacts = "/chat/common/fetchcontacts",
  sendNotification = "/notification/common/sendnotification",
  createNotification = "/notification/common/createnotification",
  fetchNotifications = "/notification/common/fetchnotifications",
  readNotifications = "/notification/common/readnotifications",
  deleteNotifications = "/notification/common/deletenotifications",
  fetchSubscriptionPlan = "/payment/common/fetchsubscriptionplan",
  fetchSubscriptionPlanById = "/payment/common/fetchsubscriptionplanbyid",
  createBookingCheckoutSession = "/payment/common/createbookingcheckoutsession",
  createSubscriptionCheckoutSession = "/payment/common/createsubscriptioncheckoutsession",
  fetchOnePaymet = "/payment/common/fetchonepaymet",
  updateSubscriptionPaymet = "payment/common/updatesubscriptionpaymet",
  updateBookingPaymet = "payment/common/updatesubbookingpaymet",
  fetchBookings = "/payment/common/fetchbookings",
  cancelBooking = "/payment/common/cancelbooking",
  fetchPaymentHistory = "/payment/common/fetchpaymenthistory",
  uploadBankStatement = "/payment/common/uploadbankstatement",
  addPaymetHistory = "/payment/common/addpaymenthistory",
  fetchFeedback = "/user/common/fetchfeedback",
  fetchAllAdvs = "/adv/common/fetchalladvs",
  fetchAllTrustedus = "/adv/common/fetchalltrustedus"

}
